# Generated by Django 5.2.3 on 2025-06-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_recommendations_content_sentiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='sentiment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
